export const queryKeys = {
  accounts: ['accounts'] as const,
  transactions: (days: number | null) => ['transactions', days] as const,
  dailySummary: ['daily-summary'] as const,
  insights: ['insights'] as const,
  budgets: ['budgets'] as const,
  cashRunway: ['cash-runway'] as const,
  forecastBridge: ['forecast-bridge'] as const,
  forecastGapOverTime: ['forecast-gap-over-time'] as const,
  forecastSnapshots: ['forecast-snapshots'] as const,
  ingestionStatus: ['ingestion-status'] as const,
  categoryPlanning: ['category-planning'] as const,
  netWorthHistory: ['net-worth-history'] as const,
  kids: ['kids'] as const,
  recurring: ['recurring'] as const,
  recurringPreferences: ['recurring-preferences'] as const,
  debt: ['debt'] as const,
  investmentReturns: ['investment-returns'] as const,
  financialHealth: ['financial-health'] as const,
  transactionForecast: ['transaction-forecast'] as const,
}
