-- Budget history: daily snapshots of forecast for "Forecast Evolution" dashboard
CREATE TABLE IF NOT EXISTS budget_history (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  category text not null,
  annual_budget numeric,
  forecast_spend numeric,
  actual_ytd numeric,
  unique (date, category)
);
