-- AI quality telemetry and weekly reports

CREATE TABLE IF NOT EXISTS ai_chat_telemetry (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  intent TEXT NOT NULL CHECK (intent IN ('finance', 'app_instructions', 'mixed', 'unknown')),
  user_query TEXT NOT NULL,
  route_hint TEXT,
  tool_calls_count INTEGER NOT NULL DEFAULT 0,
  tool_names TEXT[] NOT NULL DEFAULT '{}',
  finish_reason TEXT,
  response_text TEXT,
  response_length INTEGER NOT NULL DEFAULT 0,
  is_unanswered BOOLEAN NOT NULL DEFAULT FALSE,
  is_low_confidence BOOLEAN NOT NULL DEFAULT FALSE,
  issue_labels TEXT[] NOT NULL DEFAULT '{}',
  model TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_ai_chat_telemetry_user_created_at
  ON ai_chat_telemetry (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_chat_telemetry_created_at
  ON ai_chat_telemetry (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_chat_telemetry_unanswered
  ON ai_chat_telemetry (is_unanswered, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_chat_telemetry_low_confidence
  ON ai_chat_telemetry (is_low_confidence, created_at DESC);

ALTER TABLE ai_chat_telemetry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_own_data" ON ai_chat_telemetry;
CREATE POLICY "user_own_data" ON ai_chat_telemetry
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Weekly aggregate reports generated by cron/service role.
CREATE TABLE IF NOT EXISTS ai_quality_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  week_start DATE NOT NULL,
  week_end DATE NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  report JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ai_quality_reports_week_key UNIQUE (week_start, week_end)
);

CREATE INDEX IF NOT EXISTS idx_ai_quality_reports_week
  ON ai_quality_reports (week_start DESC, week_end DESC);

ALTER TABLE ai_quality_reports ENABLE ROW LEVEL SECURITY;
-- No policies on ai_quality_reports:
-- authenticated users cannot read/write; service role can manage.
